---

version: '{build}'
shallow_clone: true

matrix:
  fast_finish: true

environment:
  matrix:
    - perl_type: strawberry
      perl_version: 5.28.0.1

install:
  - 'call .appveyor.cmd perl_setup'
  - '%perl% -V'
  - '%cpanm% -n IO::Socket::SSL LWP::Protocol::https HTTP::Tiny'
  - '%cpanm% --installdeps -n .'

build: off

test_script:
  - '%cpanm% --test-only -v .'
